### ISSUE TITLE
[Feature Request] May I suggest you allow the buttons to wrap

### ISSUE THREAD

**Issue by shaneholloman** [tehrobber/civitai-one-click-dl#3]
```css
.mantine-1g3xmou {
    flex-flow: wrap;
}
```

this allow the site to retain its form as the no wrap that is used is a bit janked

![image](https://user-images.githubusercontent.com/1563909/218440087-605074c6-48f8-49b5-a7c0-914348890b22.png)

vs

![image](https://user-images.githubusercontent.com/1563909/218440516-63621426-3fb8-44c8-8eae-1b61f193b99f.png)
